const ActionTypes = {
  START_GAME: 'START_GAME',
  END_GAME: 'END_GAME',
  UPDATE_GAME_DATA: 'UPDATE_GAME_DATA',
  UPDATE_GAME_SEQUENCE: 'UPDATE_GAME_SEQUENCE',
  ADVANCE_ROUND: 'ADVANCE_ROUND',
};

module.exports = ActionTypes;
