const ActionTypes = {
  START_GAME: 'START_GAME',
  INCREMENT_INDEX: 'INCREMENT_INDEX',
  UPDATE_ACTIVE_COLOR: 'UPDATE_ACTIVE_COLOR',
  CLEAR_ACTIVE_COLOR: 'CLEAR_ACTIVE_COLOR',
};

module.exports = ActionTypes;
